/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.6
 * Generated at: 2018-04-03 18:42:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import pojo.FDetailsDisplay;
import java.util.ArrayList;

public final class flightDetails_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("pojo.FDetailsDisplay");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<form action = \"CustomerServlet\" method = \"post\">\r\n");
      out.write("<input type = \"hidden\" name = \"action\" value = \"flightOptions\">\r\n");
      out.write("<table>\r\n");
String flight = (String)session.getAttribute("flight");
//flight = "direct";
ArrayList<FDetailsDisplay> list = (ArrayList<FDetailsDisplay>)session.getAttribute("list");
System.out.println(list);
System.out.println(flight);
if(flight.equals("direct"))
{

      out.write("\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("<th></th>\r\n");
      out.write("<th>Airline</th>\r\n");
      out.write("<th>Flight Number</th>\r\n");
      out.write("<th>Departure Time</th>\r\n");
      out.write("<th>Arrival Time</th>\r\n");
      out.write("<th>Fare</th>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
	
for(FDetailsDisplay fdd : list)
{
	System.out.println(fdd.toString());
	
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td><input type = \"radio\" name = \"flightSelection\" value = ");
out.println(fdd.getObjectId()); 
      out.write("></td>\r\n");
      out.write("\t<td>");
out.println(fdd.getAirlineName1()); 
      out.write("</td>\r\n");
      out.write("\t<td>");
out.println(fdd.getFLightNumber1()); 
      out.write("</td>\r\n");
      out.write("\t<td>");
out.println(fdd.getDepartureTime()); 
      out.write("</td>\r\n");
      out.write("\t<td>");
out.println(fdd.getArrivalTime()); 
      out.write("\r\n");
      out.write("\t<td>");
out.println(fdd.getFare()); 
      out.write("</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t\r\n");
      out.write("\t");

}

}
else 
{
	if(flight.equals("one"))
	{
		
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t<th></th>\r\n");
      out.write("\t\t<th>Airline</th>\r\n");
      out.write("\t\t<th>Flight Number</th>\r\n");
      out.write("\t\t<th>Departure Time</th>\r\n");
      out.write("\t\t<th>Arrival Time</th>\r\n");
      out.write("\t\t<th>Total Fare</th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t");
	
		for(FDetailsDisplay fdd : list)
		{
			
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t<td><input type = \"radio\" name = \"flightSelection\" value = ");
out.println(fdd.getObjectId()); 
      out.write("></td>\r\n");
      out.write("\t\t\t<td>");
out.println(fdd.getAirlineName1()); 
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
out.println(fdd.getFLightNumber1()); 
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
out.println(fdd.getDepartureTime()); 
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
out.println(fdd.getArrivalTime()); 
      out.write("</td>\r\n");
      out.write("\t\t\t<td colspan=\"2\">");
out.println(fdd.getFare()); 
      out.write("</td></tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t<td></td>\r\n");
      out.write("\t\t\t<td>");
out.println(fdd.getAirlineName2()); 
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
out.println(fdd.getFLightNumber2()); 
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
out.println(fdd.getSecDepartureTime()); 
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
out.println(fdd.getSecArrivalTime()); 
      out.write("\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

		}

	}
	else
	{
		if(flight.equals("two"))
		{
			
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t<th></th>\r\n");
      out.write("\t\t\t<th>Airline</th>\r\n");
      out.write("\t\t\t<th>Flight Number</th>\r\n");
      out.write("\t\t\t<th>Departure Time</th>\r\n");
      out.write("\t\t\t<th>Arrival Time</th>\r\n");
      out.write("\t\t\t<th>Fare</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

			
			for(FDetailsDisplay fdd : list)
			{
				
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><input type = \"radio\" name = \"flightSelection\" value = ");
out.println(fdd.getObjectId()); 
      out.write("></td>\r\n");
      out.write("\t\t\t\t<td>");
out.println(fdd.getAirlineName1()); 
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td>");
out.println(fdd.getFLightNumber1()); 
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td>");
out.println(fdd.getDepartureTime()); 
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td>");
out.println(fdd.getArrivalTime()); 
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td colspan=\"3\">");
out.println(fdd.getFare()); 
      out.write("</td></tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t<td>");
out.println(fdd.getAirlineName2()); 
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td>");
out.println(fdd.getFLightNumber2()); 
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td>");
out.println(fdd.getSecDepartureTime()); 
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td>");
out.println(fdd.getSecArrivalTime()); 
      out.write("\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t<td>");
out.println(fdd.getAirlineName3()); 
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td>");
out.println(fdd.getFLightNumber3()); 
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td>");
out.println(fdd.getThirdDepartureTime()); 
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td>");
out.println(fdd.getThirdArrivalTime()); 
      out.write("\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t");

			}
		}
		
		else
		{
			if(flight.equals("round"))
			{
				
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th></th>\r\n");
      out.write("\t\t\t\t<th>Airline</th>\r\n");
      out.write("\t\t\t\t<th>Flight Number</th>\r\n");
      out.write("\t\t\t\t<th>Departure Time</th>\r\n");
      out.write("\t\t\t\t<th>Arrival Time</th>\r\n");
      out.write("\t\t\t\t<th>Total Fare</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t");

				
				for(FDetailsDisplay fdd : list)
				{
					
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><input type = \"radio\" name = \"flightSelection\" value = ");
out.println(fdd.getObjectId()); 
      out.write("></td>\r\n");
      out.write("\t\t\t\t\t<td>");
out.println(fdd.getAirlineName1()); 
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
out.println(fdd.getFLightNumber1()); 
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
out.println(fdd.getDepartureTime()); 
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
out.println(fdd.getArrivalTime()); 
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"2\">");
out.println(fdd.getFare()); 
      out.write("</td></tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t<td>");
out.println(fdd.getAirlineName2()); 
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
out.println(fdd.getFLightNumber2()); 
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
out.println(fdd.getSecDepartureTime()); 
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
out.println(fdd.getSecArrivalTime()); 
      out.write("\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t");

				}
			}
			else
			{
				if(flight.equals("differentDays"))
				{
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr><th rowspan = \"7\">No Flights available on selected Date</th></tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th></th>\r\n");
      out.write("\t\t\t\t\t\t<th>Date</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Airline</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Flight Number</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Departure Time</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Arrival Time</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Total Fare</th>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t");

						
						for(FDetailsDisplay fdd : list)
						{
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type = \"radio\" name = \"flightSelection\" value = ");
out.println(fdd.getObjectId()); 
      out.write("></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>");
out.println(fdd.getDateFlight()); 
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>");
out.println(fdd.getAirlineName1()); 
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>");
out.println(fdd.getFLightNumber1()); 
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>");
out.println(fdd.getDepartureTime()); 
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>");
out.println(fdd.getArrivalTime()); 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<td>");
out.println(fdd.getFare()); 
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t");

						}
				}
			}
		}
	}
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("<input type = \"submit\" value = \"Select Flight\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
